export { default as Button } from "./button/component"
export { default as Text } from "./text/component"
export { default as Icon } from "./icon/component"
export { default as Table } from "./table/component"
export { default as Loader } from "./loader/component"